apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.issuer.name }}
  namespace: {{ .Values.namespace }}
spec:
  acme:
    email: {{ .Values.issuer.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Values.issuer.name }}-private-key
    solvers:
      - http01:
          ingress:
            class: nginx