apiVersion: apps/v1
kind: Deployment
metadata:
  name: plant-coach-be
  labels:
    app: plant-coach-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plant-coach-be
  template:
    metadata:
      labels:
        app: plant-coach-be
    spec:
      containers:
      - name: plant-coach-be
        image: jmgrant/plant-coach-be:amd64-92839ca1ff856608b3629c3d24e47c39b879cf4f
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        env:
          - name: RAILS_ENV
            value: production
          - name: RAILS_MASTER_KEY
            value: 9053dc0629e486ae34af8496815541ad
          - name: POSTGRES_PORT
            value: "25060"
          - name: POSTGRES_HOST
            value: private-plant-coach-be-postgresql-cluster-do-user-21563123-0.m.db.ondigitalocean.com
          - name: POSTGRES_DB
            value: defaultdb
          - name: POSTGRES_USER
            value: doadmin
          - name: POSTGRES_PASSWORD
            value: AVNS_J4ktXjHNjr9ZE-MJUpu