name: Release Charts

on:
  push:
    # branches:
    #   - main

jobs:
  deploy:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Kubeconfig
        run: |
          mkdir /home/runner/.kube
          touch /home/runner/.kube/config
          echo "${{ secrets.KUBECONFIG }}" > /home/runner/.kube/config

      # - name: Install Helm
      #   run: |
      #     curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      #     chmod 700 get_helm.sh
      #     ./get_helm.sh

      - name: Deploy Chart
        run: |
          helm upgrade plant-coach-be . --kube-context do-nyc1-plant-coach