name: Push Helm
on: push
jobs:
  push:
    runs-on: ubuntu-latest
    name: Helm Push Demo
    steps:
      - uses: actions/checkout@v4
      - name: Push
        id: push
        uses: ./
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "helm"
          owner: "cloudsmith"
          repo: "actions"
          republish: "true" # needed ONLY if version is not changing
          file: "plant-coach-be-0.10.0.tgz"