name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Add Kubeconfig
        run: |
          mkdir /home/runner/.kube
          touch /home/runner/.kube/config
          echo "${{ secrets.KUBECONFIG }}" > /home/runner/.kube/config
      
      - name: Create Docker Registry Secret
        run: |
          kubectl get secret ${{ secrets.SECRET_NAME }}

          if [ $? -eq 0 ]; then
            echo "Secret ${{ secrets.SECRET_NAME }} already exists."
            echo "No action needed"
          else
            echo "Secret ${{ secrets.SECRET_NAME }} does not exist."
            echo "Creating secret ${{ secrets.SECRET_NAME }}."
            
            echo ${{ secrets.DOCKERHUB_CLUSTER_SECRET }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            kubectl create secret generic ${{ secrets.SECRET_NAME }} \
            --from-file=.dockerconfigjson=/home/runner/.docker/config.json \
            --type=kubernetes.io/dockerconfigjson
          fi

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"